### PR TITLE
Upgrade gemoji and fix broken link

### LINKED ISSUE #1: Plugin not showing icons
Hi there,

I installed this plugin. Please check screenshot below. Redmine version 2.5.2

image

If I inserts any emoticon in text field. The preview doesn't works. Google Chrome 36.0.1985.125

### PR DESCRIPTION
**Pull request by linc01n**
Fix #1

### CODE REVIEW

**Comment by tofi86** [comment]
This seems to be obsolete when using the latest gemoji gem 2.1.0 as they returned to bundle all icons with its name in addition to the unciode-named files.

Will release a new version of my plugin soo which comes with gemoji 2.1.0 support.

**Comment by tofi86** [comment]
@linc01n new version 0.4.0 was just released and uses new gemoji gem 2.1.0

**Comment by linc01n** [comment]
@tofi86 Thanks! I'll check it out.

**Comment by tofi86** [comment]
@linc01n don't try, it's not working. See #13 
Will have to revert to gemoji 1.5.0 or finally merge this mapping table (which won't merge anymore after 0.4.0 plugin changes...)

**Comment by tofi86** [comment]
Thanks again for your contribution but I've decided to not merge this.

If you would like faster view in the emoji selector popup, please use the version 0.6.0 pre-release with support for native Unicode emojis displayed in your system emoji font.

**Pull request closed without merging**
